compile:
	javac IllegalKeyException.java
	javac bNotEvenException.java
	javac DuplicateBTree.java
	javac BTree.java
	javac Main.java

main:
	javac BTree.java
	javac Main.java
	java Main

run:
	compile test

test:
	java Main

run: compile test

clean:
	-rm *.class